image: docker:stable

before_script:
  - docker info

build:
  stage: build
  script:
    - 'DEBVERSION=$([[ $CI_COMMIT_REF_NAME = "master" ]] && echo "unstable" || echo $CI_COMMIT_REF_NAME)'
    - docker build -t soseth/python-ci-base:$CI_COMMIT_REF_NAME --build-arg BRANCH=$DEBVERSION .
    - docker push soseth/python-ci-base:$CI_COMMIT_REF_NAME
